package com.app.harmony_chat.configs;

public interface DefineEmail {
    String ACCOUNT_ADMIN = "ltwgroup23@gmail.com";
    String ACCOUNT_TOKEN = "bvzp jdaf jubo yjis";

    String TITLE_FORGET = "HARMONY - QUAN TRỌNG, THAY ĐỔI MẬT KHẨU CỦA TÀI KHOẢN";
    String CONTENT_FORGET = "<html>"
            + "<body style='font-family:Arial,sans-serif;background-color:#f4f4f4;margin:0;padding:0;'>"
            + "<table align='center' border='0' cellpadding='0' cellspacing='0' width='600' style='border:1px solid #cccccc;'>"
            + "<tr>"
            + "<td align='center' bgcolor='#70bbd9' style='padding: 40px 0 30px 0;'>"
            + "<h1 style='color: #ffffff;'>Chào bạn!</h1>"
            + "</td>"
            + "</tr>"
            + "<tr>"
            + "<td bgcolor='#ffffff' style='padding: 40px 30px 40px 30px;'>"
            + "<p style='color: #333333; font-size: 18px;'>Xin chào, chúng tôi đến từ Harmony.</p>"
            + "<p style='color: #555555; font-size: 16px;'>Chúng tôi nhận được thông tin bạn cần đặt lại mật khẩu tài khoản của mình. Nếu đây không phải đo bạn yêu cầu hãy bỏ qua email này và làm theo các bước sau:</p>"
            + "<ul>"
            + "<oi>Truy cập vào tài khoản trên điện thoại bằng mật khẩu này</oi>"
            + "<oi>Tiến đến phần tài khoản cá nhân</oi>"
            + "<oi>Thực hiện việc thay đổi mật khẩu</oi>"
            + "</ul>"
            + "<p style='color: #555555; font-size: 16px;'>Nếu đây là yêu cầu từ bạn thì chúng tôi xin gửi mật khẩu mới tại đây: %s</p>"
            + "<p style='color: #555555; font-size: 16px;'>Trân trọng.</p>"
            + "</td>"
            + "</tr>"
            + "<tr>"
            + "<td bgcolor='#70bbd9' style='padding: 30px 30px 30px 30px;'>"
            + "<table border='0' cellpadding='0' cellspacing='0' width='100%'>"
            + "<tr>"
            + "<td width='75%' style='color:#ffffff; font-size:14px;'>"
            + "&reg; Harmony, android 2024<br/>"
            + "</td>"
            + "<td align='right'>"
            + "<table border='0' cellpadding='0' cellspacing='0'>"
            + "<tr>"
            + "<td>"
            + "<a href='https://www.twitter.com/'>"
            + "<img src='https://assets.stickpng.com/images/580b57fcd9996e24bc43c53e.png' alt='Twitter' width='38' height='38' style='display: block;' border='0'/>"
            + "</a>"
            + "</td>"
            + "<td style='font-size: 0; line-height: 0;' width='20'>&nbsp;</td>"
            + "<td>"
            + "<a href='https://www.facebook.com/'>"
            + "<img src='https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg' alt='Facebook' width='38' height='38' style='display: block;' border='0'/>"
            + "</a>"
            + "</td>"
            + "</tr>"
            + "</table>"
            + "</td>"
            + "</tr>"
            + "</table>"
            + "</td>"
            + "</tr>"
            + "</table>"
            + "</body>"
            + "</html>";

    String TITLE_REGISTER = "Xin chào, Cảm ơn bạn vì đã tin tưởng sử dụng dịch vụ của chúng tôi";
    String CONTENT_REGISTER = "<html>"
            + "<body style='font-family:Arial,sans-serif;background-color:#f4f4f4;margin:0;padding:0;'>"
            + "<table align='center' border='0' cellpadding='0' cellspacing='0' width='600' style='border:1px solid #cccccc;'>"
            + "<tr>"
            + "<td align='center' bgcolor='#70bbd9' style='padding: 40px 0 30px 0;'>"
            + "<h1 style='color: #ffffff;'>Chào bạn!</h1>"
            + "</td>"
            + "</tr>"
            + "<tr>"
            + "<td bgcolor='#ffffff' style='padding: 40px 30px 40px 30px;'>"
            + "<p style='color: #333333; font-size: 18px;'>Xin chào, chúng tôi đến từ Harmony.</p>"
            + "<p style='color: #555555; font-size: 16px;'>Xin cảm ơn bạn vì đã tin tưởng sử dụng ứng dụng của chúng tôi, với tiêu chí đem đến trải nghiệm tốt nhất cho khách hàng chúng tôi sẽ luôn cố gắng cải thiện hơn. Nếu có bất cứ thắc mắc hoặc góp ý nào xin vui lòng gửi về mail chúng tôi hoặc truy cập phần liên hệ người quản trị trong ứng dụng.</p>"
            + "<p style='color: #555555; font-size: 16px;'>Trân trọng.</p>"
            + "</td>"
            + "</tr>"
            + "<tr>"
            + "<td bgcolor='#70bbd9' style='padding: 30px 30px 30px 30px;'>"
            + "<table border='0' cellpadding='0' cellspacing='0' width='100%'>"
            + "<tr>"
            + "<td width='75%' style='color:#ffffff; font-size:14px;'>"
            + "&reg; Harmony, android 2024<br/>"
            + "</td>"
            + "<td align='right'>"
            + "<table border='0' cellpadding='0' cellspacing='0'>"
            + "<tr>"
            + "<td>"
            + "<a href='https://www.twitter.com/'>"
            + "<img src='https://assets.stickpng.com/images/580b57fcd9996e24bc43c53e.png' alt='Twitter' width='38' height='38' style='display: block;' border='0'/>"
            + "</a>"
            + "</td>"
            + "<td style='font-size: 0; line-height: 0;' width='20'>&nbsp;</td>"
            + "<td>"
            + "<a href='https://www.facebook.com/'>"
            + "<img src='https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg' alt='Facebook' width='38' height='38' style='display: block;' border='0'/>"
            + "</a>"
            + "</td>"
            + "</tr>"
            + "</table>"
            + "</td>"
            + "</tr>"
            + "</table>"
            + "</td>"
            + "</tr>"
            + "</table>"
            + "</body>"
            + "</html>";
}
